# Generated by Django 3.2.9 on 2021-12-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foo', models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third')], default='first', max_length=10)),
            ],
        ),
    ]
